### ISSUE TITLE
Add DD7002B Gateway

### ISSUE THREAD

**Issue by ViktorSchlaffer** [starkillerOG/motion-blinds#1]
Hi @starkillerOG,

I have a DD7002B bridge, that uses a very similar interface as the one implemented in your code.
If I make a pull request, would you integrate it in your repo, or you prefer me to fork your repo instead, and do my own thing.
(I'd just make an abstract class and put the common parts there, and move your global variables (device types and such) to the constructor of your class)

Thanks in advance for your answer.
Br,
Viktor

**Comment by starkillerOG** [comment]
Hi @ViktorSchlaffer 

I am always open to pull request.

Do you have a programming manual for the DD7002B bridge?

The commands and structure need to be almost identical to make sense to implement it in this library, otherwise it is probably better to just create a seprate library called someting like "dd7002b-bridge"

If you make a fork I can look how much impact it would have on the general Motion Gateways and then I could better judge if including it in this library makes sense or if 2 seprate libs would make more sense.

Best regards,
StarkillerOG

**Comment by starkillerOG** [comment]
I think it will be better to have a seperate library for the DD7002B bridge, unless someone can point out that this code almost works flauwless with that bridge (only very small adjustments needed).

This library is really focused on Motion Blinds from Coullisse B.V.
