### ISSUE TITLE
Question: why are you using pycryptodomex?

### ISSUE THREAD

**Issue by onkelbeh** [starkillerOG/motion-blinds#2]
Hi,

may I ask: why are you using pycryptodomex and not pycryptodome?

When I walk through Home Assitants dependency tree, I find 14 packages depending on pycryptodome, and 2 (including you) requiring pycryptodomex. It's a bad thing that both libraries install themselves as pycryptodome. This results in a slot conflict.

I hope you don't mind that I added your integration to [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository).

 \B.

**Comment by starkillerOG** [comment]
Hi Onkelbeh,

Because I had issues with pycryptodome not installing correctly on my stystem.
At least the `from Cryptodome.Cipher import AES` gave some errors which I had a hard time resolving.
Maybe it was something I was doing wrong.

With pycryptodomex I had no issues what soever, it installed cleanly and `from Cryptodome.Cipher import AES` just worked.

That is why I chose pycryptodomex, but if you insist I could look into pycryptodome some more and see if I can reslove those errors and get it to work with pycryptodome.

Of course this code can be used in other projects!
Happy to be of help!

Best regards,
StarkillerOG

**Comment by onkelbeh** [comment]
Hi,

thanks for your answer. I do not know any of these two libraries.

I just noticed this possible incompatibility some time ago and try to avoid future incompatibilities. Imho these libraries cannot live in the same environment together, so somehow some integrations cannot be installed on the same system.

**But**, I just looked in my site-packages on the Python 3.9 dev box, it seems that now pycryptodome installs itself in `Crypto` and pycryptodomex installs in `Cryptodome`. Perhaps I am talking bullshit and my knowledge is outdated.

For your info: after a bigger cleanup I grep the following components currently use `pycryptodome`:

1. coinbase
2. gogogate2-api
3. greeclimate
4. HAP-python
5. httpsig (has some more downstream deps)
6. lakeside
7. panasonic-viera
8. pycarwings2
9. pyrainbird
10. pyrecswitch
11. python-jose (has some more downstream deps)
12. python-jose-cryptodome (has some more downstream deps)
13. samsungctl
14. sucks
15. temescal
16. zigpy (many users)
17. zigpy-homeassistant  (many users)

and these use `pycyptodomex`:

1. csrmesh
2. gogogate2-api (only in older versions, these guys migrated)
3. motionblinds
4. pygogogate2 (outdated)
5. pyps4-2ndscreen

Hope this helps more than it confuses :-)

**Comment by onkelbeh** [comment]
Just checked: same on Python 3.8.

**Comment by starkillerOG** [comment]
Alright, I looked into it some more and found the most relevant info here: https://stackoverflow.com/questions/48155294/what-is-pycryptodomex-and-how-does-it-differ-from-pycryptodome

Indeed you are right that `from Crypto.Cipher import AES` works if you install pycryptodome.
However, pycryptodome installs in Crypto and can therefore cause conflicts with PyCrypto (which I had while trying diffrent options), 
pycyptodomex installs in Cryptodome and can therefore never cause conflicts.

That means I think pycyptodomex is better than pycryptodome in order to prevent conflicts.

I will close this issue since I thinks it makes most sence to stick with pycyptodomex, feel free to re-open.
