### ISSUE TITLE
Invalid syntax when interacting with Python module

### ISSUE THREAD

**Issue by electrextech** [starkillerOG/motion-blinds#26]
My apologies in advance if this is a stupid question, I am still becoming familiar with Python, though I cannot get this module set up at all, receiving the same error every time.

Perhaps I am interacting with the file wrong? I have tried both with the command line and a .py file, both have the same result. I would really appreciate any help, thank you in advance!

```
>>> from motionblinds import MotionGateway
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "motionblinds/__init__.py", line 17, in <module>
    from .motion_blinds import MotionGateway
  File "motionblinds/motion_blinds.py", line 376
    ip: str = None,
      ^
SyntaxError: invalid syntax

**Comment by starkillerOG** [comment]
Did you try updating to the latest version of this module `pip3 install --upgrade motionblinds`?
What version of python are you running?
This is tested to work with Python 3.10.

**Comment by starkillerOG** [comment]
It looks like its a python version problem.
I think this library requires at least python 3.6

**Comment by starkillerOG** [comment]
@electrextech I uploaded a new version of motionblinds 0.6.12 that now is tested with python 3.6 to 3.10. Indeed on python <3.6 you would get errors.
I now also added a requirement python >=3.6 so that the motionblinds module can not be installed with lower python versions and will produce a error message indicating you need to update the python version.

Thank you for reporting this issue.
If you appreciate the motionblinds library, consider sponsering it.

I will close this issue now, since I am almost certain this is due to the python version.
If not, or you are experiancing aditional problems, please re-open the issue or create a new one.
