### ISSUE TITLE
Error in voltage reports.

### ISSUE THREAD

**Issue by sygys** [starkillerOG/motion-blinds#28]
as of version 2022.8 in home assistant i have received around 10.000 log errors stating the following:

![Schermafbeelding 2022-08-30 114946](https://user-images.githubusercontent.com/73538763/187406585-a5f3cfcd-44d1-404e-b872-5cfa4cebed81.png)

I guess a typo in the code?

**Comment by starkillerOG** [comment]
@sygys sorry for taking so long.
I have solved the issue in the latest version of motionblinds which is already included in the HomeAssistant main git.
So the next release of HomeAssistant 2022.10 will have this fixed (the log level has been reduced to debug).

If you appreciate the motion blinds integration, please consider sponsoring this library: https://github.com/sponsors/starkillerOG

I will close this now since the issue will be resolved in the next HA release.
Please feal free to open another issue if you have aditional questions or problems.
