### ISSUE TITLE
Motion Blinds showing shades as Unknown status

### ISSUE THREAD

**Issue by jancantor** [starkillerOG/motion-blinds#34]
I have successfully integrated 7 roller battery powered shades to HA with the DD7002B gateway. I can successfully control the shades such as open, close and stop. However, the status of all shades remain Unknown regardless of the action. 
 
When I connected the gateway to HA initially, they were on a separate VLAN. Gateway was on the IoT VLAN and while HA is on its own VLAN having only allowed access to IoT, vice versa. Like I said above, the controls functions great but the status doesn't is stuck in Unknown. 

I now moved the gateway to the HA VLAN. I also disabled IGMP snooping and Multicast Enhancement per documentation. However, not much luck as well.

I’m going to try to move the both of them to the IoT VLAN next but I would expect the same result as the above. 

Unfortunately, I cannot make automation because the status doesn’t change from being Unknown. 

Please advice.

**Comment by starkillerOG** [comment]
@jancantor do you see the current position in the manufactures app of the shades?
Some models/brands of shades do not support position status, but only allow to be controlled using open/close/stop.

In HomeAssistant if you go to settings->devices&services -> motion blinds -> x devices -> select one of your shades,
In the top left what does it say after `Hardware: `?

**Comment by jancantor** [comment]
@starkillerOG the Connector app is displaying the status, Closed, Open and Stop. Hardware is UniDirection. I just bought a Sonof Bridge. Hopefully, the new hardware would fix the issue.

**Comment by starkillerOG** [comment]
@jancantor UniDirection blinds can only receive commands but cannot respond with there current position.
Therefore it is impossible to accuretly know the position of the blind.

The Connector app will just show the last command that it send to the blind.
However if you control the blind using a remote directly for example, the Connector app will not know about this and the status would be wrong in the Connector app.

In HomeAssistant the status will only be shown if we actually know the status of the device. Assumed states from last send commands are not allowed since this can cause confusion and issues with automations since it will not always be correct.

Sorry I could not help you.
If you just bought the roller blinds, maybe you could return them and get BiDirectional blinds that can respond and report there position.

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) this library.
